### ISSUE TITLE
Quantiphyse error on opening

### ISSUE THREAD

**Issue by AshwatiV** [ibme-qubic/quantiphyse#35] opened 2020-08-13 09:36 UTC
Hi I'm trying to open Quantiphyse for the first time. When I open the application, a window pops up with the terms and conditions. But it is unable to accept the "ok" open even though I keep clicking it. Help please! I am unable to move ahead or try out the program because of this issue.
<img width="1386" alt="Screenshot 2020-08-13 at 5 36 00 PM" src="https://user-images.githubusercontent.com/69627222/90118944-8765a680-dd8b-11ea-8070-8256b584052f.png">

**Comment by mcraig-ibme** [comment] 2021-01-22 15:27
Apologies for the slow response. If this is still causing you an issue could open a terminal, activate the Conda environment you have installed Quantiphyse into (if relevant) and post the output of `pip show pyside2`.

The problem is probably a bug in the underlying GUI toolkit and most likely can be solved by installing a slightly different version.

**Comment by mcraig-ibme** [comment] 2023-03-16 10:01
Closing as not reproducible elsewhere and most likely a Qt/Pyside bug. Can reopen if still occurring.

**Closed as completed by mcraig-ibme** 2023-03-16 10:01 UTC
