### ISSUE TITLE
Quantiphyse Installation problem

### ISSUE THREAD

**Issue by MinaKim00** [ibme-qubic/quantiphyse#33] opened 2019-11-21 17:07 UTC
After installation in Mac OS, I call "quantiphyse" and get the error message as follows:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/quantiphyse", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 851, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.8.0rc1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('numpy>=1.12.0'), set(['pandas']))

Please help!

**Comment by mcraig-ibme** [comment] 2019-12-04 09:59
Looks like the version of numpy you have is too old. Are you using the default Python on a Mac? It does tend to be quite behind the times.

The following may help:

sudo pip install numpy --upgrade

**Comment by MinaKim00** [comment] 2019-12-04 10:11
Thanks for your response.  I am using Python 2.7 which I installed.

After upgrading the numpy, I still get the error messages as attached.  Any idea?

**Comment by mcraig-ibme** [comment] 2019-12-04 10:18
I found a suggestion that the Mac default numpy is not removed when upgrading it and this can be fixed by the following:

cd /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/
sudo rm -r numpy
pip install pandas

It should pull in the version of Numpy that it needs. If this fails I have a Mac that I can try to reproduce this on - what MacOS version are you running?

**Comment by MinaKim00** [comment] 2019-12-04 10:20
After "sudo rm -r numpy”, I see "override rw-r--r--  root/wheel restricted,compressed for numpy/distutils/unixccompiler.py”.  What should I do?

**Comment by mcraig-ibme** [comment] 2019-12-04 10:23
Change it to sudo rm -rf numpy

It shouldn't ask you any questions then!

**Comment by MinaKim00** [comment] 2019-12-04 10:26
After that, a bunch of lines saying 

"rm: numpy/distutils/unixccompiler.py: Operation not permitted
rm: numpy/distutils/numpy_distribution.py: Operation not permitted
rm: numpy/distutils/conv_template.py: Operation not permitted
rm: numpy/distutils/cpuinfo.py: Operation not permitted
rm: numpy/distutils/ccompiler.py: Operation not permitted
rm: numpy/distutils/misc_util.pyc: Operation not permitted
rm: numpy/distutils/npy_pkg_config.py: Operation not permitted
rm: numpy/distutils/__config__.pyc: Operation not permitted
rm: numpy/distutils/compat.py: Operation not permitted
rm: numpy/distutils/system_info.pyc: Operation not permitted
rm: numpy/distutils/misc_util.py: Operation not permitted
A lot more below…."

**Comment by mcraig-ibme** [comment] 2019-12-04 10:36
This seems to be extra security on recent Macs... I found an article (linked below) which explains how to get around the problem, however I am wondering at this point if it is more sensible to go down the Anaconda route. The 'official' Mac support for Python has always been very out of date - in the past it wasn't possible to install quantiphyse at all with the standard python - and even if we can get around this issue you might find another similar problem with another package.

My recommendation at this point would be do go to www.anaconda.org, download anaconda (python 3.7) and then follow the instructions here:

https://quantiphyse.readthedocs.io/en/latest/basics/install.html#anaconda-python-3-x-dependencies-from-pip

If you want to press on using the system Python, here is the article on getting around the 'Operation not permitted' problem:

http://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/

Let me know what you try and how you get on - I am sorry it's not more straightforward unfortunately Python on Mac isn't the easiest environment to support and each new version seems to break the recipe we had working previously!

**Comment by MinaKim00** [comment] 2019-12-04 10:42
Thanks a lot for your suggestions.  I will try Anaconda then.

BTW, I have found the Basil (asl_gui) from the FSL package that I installed on my Mac.  How different is it from quantiphyse in terms of ASL data analysis?  FYI, I am going to analyse pCASL data.

**Comment by mcraig-ibme** [comment] 2019-12-04 11:03
The Basil GUI from FSL delivers a very similar ASL analysis to Quantiphyse. Technically they are using different pipelines, Basil uses oxford_asl whereas Quantiphyse uses our newer Python-based oxasl pipeline. However oxasl has been designed to mimic oxford_asl as closely as possible so you should find very similar results for the two.

oxasl (and hence Quantiphyse) is able to handle some additional ASL data types, such as multiphase and vessel-encoded data. On the other hand oxford_asl has been more extensively used. The Quantiphyse gui offers far more than the Basil GUI which is really just a front end to running the analysis. 

Hope this helps!

**Comment by mcraig-ibme** [comment] 2020-04-17 11:19
I've updated the installation instructions on Mac slightly to recommend fslpython or anaconda. I will close this issue now, problems with other installation methods can be raised as new issues.

**Closed as completed by mcraig-ibme** 2020-04-17 11:19 UTC
